version: '3'
services:
  restaurant-frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: restaurant-frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8002:3000
    env_file:
      - .env
    command: npm run start

volumes:
 .: